// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PerformerDatabaseImplements;
using System;

namespace PerformerDatabaseImplements.Migrations
{
    [DbContext(typeof(PerformerDatabaseContext))]
    partial class PerformerDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PerformerDatabaseImplements.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientName")
                        .IsRequired();

                    b.Property<string>("ClientSurame")
                        .IsRequired();

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Mail")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Tel")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PerformerDatabaseImplements.Models.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClientId");

                    b.Property<int>("Duration");

                    b.Property<decimal>("Price");

                    b.Property<string>("ProcedureName")
                        .IsRequired();

                    b.Property<int?>("PurchaseId");

                    b.Property<int?>("VisitId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("VisitId");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("PerformerDatabaseImplements.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClientId");

                    b.Property<DateTime>("Date");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("PerformerDatabaseImplements.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClientId");

                    b.Property<DateTime>("Date");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("PerformerDatabaseImplements.Models.Procedure", b =>
                {
                    b.HasOne("PerformerDatabaseImplements.Models.Client", "Client")
                        .WithMany("Procedure")
                        .HasForeignKey("ClientId");

                    b.HasOne("PerformerDatabaseImplements.Models.Purchase", "Purchase")
                        .WithMany("Procedures")
                        .HasForeignKey("PurchaseId");

                    b.HasOne("PerformerDatabaseImplements.Models.Visit", "Visit")
                        .WithMany("Procedures")
                        .HasForeignKey("VisitId");
                });

            modelBuilder.Entity("PerformerDatabaseImplements.Models.Purchase", b =>
                {
                    b.HasOne("PerformerDatabaseImplements.Models.Client", "Client")
                        .WithMany("Purchase")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("PerformerDatabaseImplements.Models.Visit", b =>
                {
                    b.HasOne("PerformerDatabaseImplements.Models.Client", "Client")
                        .WithMany("Visit")
                        .HasForeignKey("ClientId");
                });
#pragma warning restore 612, 618
        }
    }
}
